FROM alpine:latest
EXPOSE 5000
WORKDIR /opt/
RUN apk add python3 py-pip
ADD requirements.txt .
RUN pip install -r requirements.txt
ADD index.html .
ADD top.html .
ADD quotes_frontend.py .
ENTRYPOINT python quotes_frontend.py