# Only used for testing before deployed to K8s.

version: "3"
services:
  frontend:
    hostname: quotes-frontend
    container_name: quotes-frontend
    build: frontend/
    ports:
      - "80:5000"
    depends_on:
      - backend
    environment:
      BACKEND_URI: "http://quotes-backend:5000"
      EXTERNAL_BROWSER_URI: "http://localhost:5000"

  backend:
    hostname: quotes-backend
    container_name: quotes-backend
    build: backend/
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      MONGODB_URI: "mongodb://quotes-database:27017"

  database:
    hostname: quotes-database
    container_name: quotes-database
    image: "mongo:latest"
    ports:
      - "27017:27017"

# docker exec -i quotes-database mongosh localhost:27017 <<EOF
# use quotes_db
# db.quotes_col.insertMany(
#     [{author: "Mahatma Gandhi", quote: "You must be the change you wish to see in the world.", score: 0},
#     {author: "Mother Teresa", quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", score: 0},
#     {author: "Franklin D. Roosevelt", quote: "The only thing we have to fear is fear itself.", score: 0},
#     {author: "Martin Luther King Jr.", quote: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", score: 0},
#     {author: "Eleanor Roosevelt", quote: "Do one thing every day that scares you.", score: 0},
#     {author: "Benjamin Franklin", quote: "Well done is better than well said.", score: 0},
#     {author: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", quote: "Helen Keller", score: 0},
#     {author: "It is during our darkest moments that we must focus to see the light.", quote: "Aristotle", score: 0},
#     {author: "Do not go where the path may lead, go instead where there is no path and leave a trail.", quote: "Ralph Waldo Emerson", score: 0},
#     {author: "Be yourself; everyone else is already taken.", quote: "Oscar Wilde", score: 0},
#     {author: "If life were predictable it would cease to be life and be without flavor.", quote: "Eleanor Roosevelt", score: 0},
#     {author: "In the end, it's not the years in your life that count. It's the life in your years.", quote: "Abraham Lincoln", score: 0},
#     {author: "Life is a succession of lessons which must be lived to be understood.", quote: "Ralph Waldo Emerson", score: 0},
#     {author: "You will face many defeats in life, but never let yourself be defeated.", quote: "Maya Angelou", score: 0},
#     {author: "Never let the fear of striking out keep you from playing the game.", quote: "Babe Ruth", score: 0},
#     {author: "Life is never fair, and perhaps it is a good thing for most of us that it is not.", quote: "Oscar Wilde", score: 0},
#     {author: "The only impossible journey is the one you never begin.", quote: "Tony Robbins", score: 0},
#     {author: "In this life we cannot do great things. We can only do small things with great love.", quote: "Mother Teresa", score: 0},
#     {author: "Only a life lived for others is a life worthwhile.", quote: "Albert Einstein", score: 0},
#     {author: "The purpose of our lives is to be happy.", quote: "Dalai Lama", score: 0}],
#     {ordered: false})
# EOF