---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes-database
  template:
    metadata:
      labels:
        app: quotes-database
    spec:
      containers:
      - name: quotes-database
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: quotes-database-storage
          mountPath: /data/db
      volumes:
      - name: quotes-database-storage
        persistentVolumeClaim:
          claimName: quotes-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-database-service
spec:
  selector:
    app: quotes-database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quotes-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: quotes-database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongodb/data
---